spring:
  application:
    name: my-sky

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sky_take_out
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# application.yml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: hasdiofhkljsahdfljkhsadbnfklasbdfjihsadflkjhasdlkjfhsidlfuhasdkjlfhbasdkflghskludjfh
    # 设置jwt过期时间
    admin-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: hasdiofhkljsahdfljkhsadbnfkasvaasewe123sbdfjihsadflkjhasdlkjfhsidlfuhasdkjlfhbasdkflghskludjfh
    user-ttl: 7200000
    user-token-name: authentication
  wechat:
    appid: wx702ac0455f09b018
    secret: 39c941940578eda748057875cb170c7b

# 阿里云oss
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: ${ALIBABA_ACCESS_KEY_ID}
    accessKeySecret: ${ALIBABA_ACCESS_KEY_SECRET}
    bucketName: chengzi03


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs